language: cpp

dist: trusty
sudo: required

# Configure Os to use
matrix:
  include:
    - os: osx
      env: PLATFORM="native_dyn"
  exclude:
    - os: linux

before_install:
- openssl aes-256-cbc -K $encrypted_eba2f7543984_key -iv $encrypted_eba2f7543984_iv
  -in travis/travisci_builder_id_key.enc -out travis/travisci_builder_id_key -d
- chmod 600 travis/travisci_builder_id_key
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  ccache: true
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
install: travis/install_extra_deps.sh
script: travis_wait 30 travis/compile_all.sh
deploy:
  provider: script
  skip_cleanup: true
  script: travis/deploy.sh
  on:
    condition: ( "$TRAVIS_EVENT_TYPE" = "cron" )
env:
 - PLATFORM="native_dyn"
 - PLATFORM="native_static"
 - PLATFORM="win32_dyn" OS_ONLY="linux"
 - PLATFORM="win32_static" OS_ONLY="linux"
 - PLATFORM="armhf_dyn" OS_ONLY="linux"
 - PLATFORM="armhf_static" OS_ONLY="linux"
 - PLATFORM="android_arm" OS_ONLY="linux"
 - PLATFORM="android_arm64" OS_ONLY="linux"
 - PLATFORM="android_mips" OS_ONLY="linux"
 - PLATFORM="android_mips64" OS_ONLY="linux"
 - PLATFORM="android_x86" OS_ONLY="linux"
 - PLATFORM="android_x86_64" OS_ONLY="linux"
notifications:
  irc:
    channels:
     - "chat.freenode.net#kiwix"
    on_success: change
    on_failure: always
addons:
  ssh_known_hosts: download.kiwix.org
